ARG BASE_IMAGE=registry.wifx.net/yocto/lorix-os/build-system/rootless

FROM $BASE_IMAGE

# Install/Update git to at least v2.36.1 from PPA and install sudo.
RUN apt-get update && \
    apt-get install -y --no-install-recommends gnupg gpg-agent software-properties-common && \
    add-apt-repository -y ppa:git-core/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends git sudo && \
    apt-get purge -y --auto-remove software-properties-common gnupg gpg-agent && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a non-root user that will perform the actual build
RUN id build 2>/dev/null || useradd --uid 5000 --create-home build

# Configure sudoers for the build user
RUN echo "build ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers

# Set ownership of /yocto directory for the build user
# The /yocto directory is created in the BASE_IMAGE.
RUN chown build:build /yocto

USER build

RUN git config --global --add safe.directory '*'

# EOF
