FROM ubuntu:22.04

LABEL org.opencontainers.image.authors="Wifx <support@iot.wifx.net>"

ENV DEBIAN_FRONTEND=noninteractive

# Required Packages for the Host Development System & Additional host packages required by poky/scripts/wic
# http://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#required-packages-for-the-host-development-system
RUN apt-get update && apt-get install -y --no-install-recommends \
     gawk wget diffstat unzip texinfo \
     gcc-multilib g++-multilib build-essential chrpath socat cpio \
     python3 python3-pip python3-pexpect apt-utils tmux xz-utils debianutils \
     iputils-ping libncurses5-dev git-lfs libssl-dev liblz4-tool zstd file \
     curl dosfstools mtools parted syslinux tree jq \
     locales \
     openssh-client \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

# Add "repo" tool (used by many Yocto-based projects)
RUN curl -o /usr/local/bin/repo http://storage.googleapis.com/git-repo-downloads/repo && \
    chmod a+x /usr/local/bin/repo

# Create yocto directory that will contain downloads and sstate cache (can be overridden by volume)
RUN mkdir /yocto

# Fix error "Please use a locale setting which supports utf-8."
# See https://wiki.yoctoproject.org/wiki/TipsAndTricks/ResolvingLocaleIssues
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_US.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

WORKDIR /yocto
CMD ["/bin/bash"]

# EOF
