ARG BASE_IMAGE=registry.wifx.net/yocto/lorix-os/build-system/rootless

# Prebuild for git v2.36.1 which support wildcard for unsafe directory exception
FROM ubuntu:20.04 as git-build
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y dh-autoreconf libcurl4-gnutls-dev libexpat1-dev gettext \
    libz-dev libssl-dev gcc-multilib build-essential unzip wget
RUN wget https://codeload.github.com/git/git/zip/refs/tags/v2.36.1
RUN mv v2.36.1 git.zip
RUN unzip git.zip
WORKDIR /git-2.36.1
# Configure
RUN make configure
RUN ./configure --prefix=/usr
# Build
RUN make all -j16
# Install
RUN mkdir /build
RUN make DESTDIR=/build install

FROM $BASE_IMAGE

# Install manually compiled git
COPY --from=git-build /build/ /usr/

# Create a non-root user that will perform the actual build
RUN id build 2>/dev/null || useradd --uid 5000 --create-home build
RUN apt install -y sudo
RUN echo "build ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers

# Create yocto directory that will contain downloads and sstate cache (can be overridden by volume)
RUN chown build:build /yocto

USER build

# EOF
