# SSH input rules chain
table inet filter {

    # SSH brute force protection set (blacklist)
    set ssh_bruteforce {
        type ipv4_addr
        timeout 1m
        size 256
        flags dynamic
    }

    set ssh6_bruteforce {
        type ipv6_addr
        timeout 1m
        size 256
        flags dynamic
    }

    # SSH protection chain
    chain sshprotect {
        update @ssh_bruteforce { ip saddr limit rate over 3/minute } drop comment "SSH: Block IPv4 brute force"
        update @ssh6_bruteforce { ip6 saddr limit rate over 3/minute } drop comment "SSH: Block IPv6 brute force"
        
        accept comment "SSH: Accept normal SSH connections"
    }

    # SSH input chain
    chain input {
        # SSH with brute force protection for both IPv4 and IPv6
        tcp dport 22 tcp flags & (fin|syn|rst|ack) == syn ct state new jump sshprotect comment "SSH with brute force protection"
    }
}
