#!/sbin/openrc-run
# Copyright (c) 2019-2020, Wifx Sàrl <info@wifx.net>
# All rights reserved.

CHIP=${LORA_CORE_RST_CHIP:-gpiochip0}
PIN=${LORA_CORE_RST_PIN:-1}
DELAY=${LORA_CORE_RST_DELAY_MS:-100}

extra_commands="reset"

depend() {
    need sysfs
}

reset() {
    ebegin "Resetting the LoRa concentrator"

    /usr/sbin/lora-concentrator-reset

    eend 0
}

start() {
    ebegin "Staring lora concentrator service"
    reset
}

stop() { 
    ebegin "Stopping lora concentrator service (no hardware operation is done)"
    eend 0
}
