keypair = "/etc/opt/helium-gateway/key.bin"
listen_addr = "127.0.0.1:1680"
region = "EU868"

[log]
method = "syslog"
level = "info"
timestamp = false

[update]
# Enable update checking
enabled = false

# A list of gateway service keys and urls (note https is not supported
[[gateways]]
# ohio2
public_key = "112AY1cJ9quokGVZL8uVQ9Jih1cHsji2VVoKApf2fVPBseHcRsgA"
uri = "http://18.216.219.228:8080"


## Default router
[router]
# dev
#public_key = "1124CJ9yJaHq4D6ugyPCDnSBzQik61C1BqD9VMh1vsUmjwt16HNB"
#uri = "http://54.176.88.149:8080"
# staging
public_key = "11263KvqW3GZPAvag5sQYtBJSjb25azSTSwoi5Tza9kboaLRxcsv"
uri = "http://54.193.165.228:8080"
# production
#public_key = "112qB3YaH5bZkCnKA5uRH7tBtGNv2Y5B4smv1jsmvGUzgKT71QpE"
#uri = "http://52.8.80.146:8080"