# Concentratord configuration.
#
# https://www.chirpstack.io/concentratord/install/config/

[concentratord]

  # Log level.
  #
  # Valid options are:
  #   * TRACE
  #   * DEBUG
  #   * INFO
  #   * WARN
  #   * ERROR
  #   * OFF
  log_level="INFO"

  # Statistics interval.
  stats_interval="30s"

  # Configuration for the (ZeroMQ based) API.
  [concentratord.api]

    # Event PUB socket bind.
    event_bind="ipc:///tmp/concentratord_event"

    # Command REP socket bind.
    command_bind="ipc:///tmp/concentratord_command"
