description: ChirpStack Gateway Bridge with concentratord
autostart: true
log: true
jobs:
    concentratord:
        description: The daemon receiving data from the LoRa concentrator (SX13XX) and forwarding to the Gateway Bridge
        process:
            run-mode: exec
            program-path: /opt/chirpstack-concentratord/chirpstack-concentratord
            program-arguments: -c /etc/opt/chirpstack-concentratord/00-concentratord.toml -c /etc/opt/chirpstack-concentratord/10-gateway.toml -c /etc/opt/chirpstack-concentratord/channels/channels.toml
            delays:
                start: 3000
                term: 1000
                restart: 5000
    gateway-bridge:
        description: Gateway Bridge receiveing the cocnentrator daemon packets and sending them to the ChirpStack Network Server
        process:
            run-mode: exec
            program-path: /opt/chirpstack-gateway-bridge/chirpstack-gateway-bridge
            program-arguments: -c /etc/opt/chirpstack-gateway-bridge/10-general.toml -c /etc/opt/chirpstack-gateway-bridge/20-backend_concentratord.toml -c /etc/opt/chirpstack-gateway-bridge/30-integration.toml -c /etc/opt/chirpstack-gateway-bridge/40-filters.toml
            delays:
                start: 1000
                term: 1000
                restart: 5000
