#!/sbin/openrc-run
# Copyright (c) 2023, Wifx SA <info@iot.wifx.net>
# All rights reserved.

INHIBIT_FILE="/run/wwan-modem-check.inhibit"
CHIP=${WWAN_PWR_CHIP:-gpiochip3}
PIN=${WWAN_PWR_PIN:-18}

depend() {
    need sysfs
    after modules-load
}

start() {
    ebegin "Powering up the WWAN modem"

    # TODO: should be abstracted through machine-info
    gpioset --toggle 0 --chip ${CHIP} ${PIN}=1

    # Restore wwan check
    rm -f $INHIBIT_FILE
}

stop() {
    ebegin "Powering down the WWAN modem"
    
    # Inhibit wwan check
    touch $INHIBIT_FILE

    # TODO: should be abstracted through machine-info
    gpioset --toggle 0 --chip ${CHIP} ${PIN}=0
}
