description: UDP packet forwarder with the ChirpStack Packet Multiplexer
autostart: true
log: true
jobs:
    udp-packet-forwarder:
        description: The forwarder receiving data from the SPI (SX13XX) and forwarding to the Gateway Bridge
        process:
            run-mode: exec
            program-path: /opt/udp-packet-forwarder/udp-packet-forwarder
            program-arguments: -H /etc/opt/udp-packet-forwarder/hardware/hardware_conf.json -C /etc/opt/udp-packet-forwarder/channels/channels_conf.json -c /etc/opt/udp-packet-forwarder/gateway/chirpstack-gateway-bridge
            delays:
                start: 5000
                term: 10000
                restart: 5000

    chirpstack-packet-multiplexer:
        description: The ChirpStack Packet Multiplexer utility forwards the packet-forwarder UDP data to multiple endpoints.
        process:
            run-mode: exec
            program-path: /opt/chirpstack-packet-multiplexer/chirpstack-packet-multiplexer
            program-arguments: -c /etc/opt/chirpstack-packet-multiplexer/chirpstack-packet-multiplexer.toml
            delays:
                start: 2000
                term: 5000
                restart: 5000
