# +++
# name: Europe 863-870 MHz (SF12 for RX2)
# description: Default frequency plan for Europe
# countries: [AL, AD, AO, AT, BH, BE, BA, BW, BG, CG, HR, CY, CZ, DK, EE, SZ, FI, FR, GR, HU, IS, IE, IT, LV, LS, LI, LT, LU, MG, MW, MT, MU, MD, ME, MZ, NA, NL, MK, PH, PL, PT, RO, RU, SA, RS, SC, SK, SI, ZA, ES, SE, CH, TZ, TR, AE, GB, VA, ZM, ZW]
# +++


# LoRa concentrator configuration.
[gateway.concentrator]

    # Multi spreading-factor channels (LoRa).
    multi_sf_channels=[
        868100000,
        868300000,
        868500000,
        867100000,
        867300000,
        867500000,
        867700000,
        867900000,
    ]

    # LoRa std channel (single spreading-factor).
    [gateway.concentrator.lora_std]
        frequency=868300000
        bandwidth=250000
        spreading_factor=7

    # FSK channel.
    [gateway.concentrator.fsk]
        frequency=868800000
        bandwidth=125000
        datarate=50000
