# LoRa gateway configuration of the concentratord
#
# You can update the gateway configuration for the concentratord here.
# Refer to https://www.chirpstack.io/concentratord/install/config/ for details
#
# NOTE: The LORIX Manager will override the antenna_gain setting if defined in the Manager

[gateway]

  # Public LoRaWAN network.
  lorawan_public=true

  # Antenna gain (dB).
  antenna_gain=0
  
  model="wifx_l1_863_870"
