description: Helium Gateway with an UDP Packet Forwarder
autostart: true
log: true
jobs:
    helium-gateway:
        description: Helium Gateway packet forwarder
        boot-order: 0
        process:
            run-mode: exec
            program-path: /opt/helium-gateway/helium-gateway
            program-arguments: -c /etc/opt/helium-gateway/settings.toml server
            delays:
                start: 5000
                term: 10000
                restart: 5000
    udp-packet-forwarder:
        description: The daemon receiving data from the LoRa concentrator (SX13XX) and forwarding to the Helium Gateway packet forwarder
        boot-order: 1
        process:
            run-mode: exec
            program-path: /opt/udp-packet-forwarder/udp-packet-forwarder
            program-arguments: >-
              -H /etc/opt/udp-packet-forwarder/hardware/hardware_conf.json
              -C /etc/opt/udp-packet-forwarder/channels/channels_conf.json
              -c /etc/opt/udp-packet-forwarder/gateway/chirpstack-gateway-bridge
            delays:
                start: 5000
                term: 10000
                restart: 5000
