# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rust-wifx-mixin-scarthgap"
BBFILE_PATTERN_meta-rust-wifx-mixin-scarthgap = "^${LAYERDIR}/"

# Priority must just be higher than OE core (5)
# but it is not sufficient for *.bbclass override so this layer needs to be
# parsed before meta-oe in bblayers.conf
BBFILE_PRIORITY_meta-rust-wifx-mixin-scarthgap = "6"

LAYERSERIES_COMPAT_meta-rust-wifx-mixin-scarthgap = "scarthgap"

LAYERDEPENDS_meta-rust-wifx-mixin-scarthgap = "core"

LICENSE_PATH += "${LAYERDIR}/licenses"
