description: ChirpStack concentratord with an UDP Bridge
autostart: true
log: true
jobs:
    concentratord:
        description: LoRa concentrator daemon
        boot-order: 0
        process:
            run-mode: exec
            program-path: /opt/chirpstack-concentratord/chirpstack-concentratord
            program-arguments: -c /etc/opt/chirpstack-concentratord/00-concentratord.toml -c /etc/opt/chirpstack-concentratord/10-gateway.toml -c /etc/opt/chirpstack-concentratord/channels/channels.toml
            delays:
                start: 5000
                term: 5000
                restart: 5000
    udp-bridge:
        description: Bridges the concentratord to and UDP server
        boot-order: 1
        process:
            run-mode: exec
            program-path: /opt/chirpstack-udp-bridge/chirpstack-udp-bridge
            program-arguments: -c /etc/opt/chirpstack-udp-bridge/00-concentratord.toml -c /etc/opt/chirpstack-udp-bridge/10-udp-bridge.toml -c /etc/opt/chirpstack-udp-bridge/20-servers.toml
            delays:
                start: 5000
                term: 10000
                restart: 5000
