# +++
# name: Asia 923-925 MHz
# description: TTN Community Network frequency plan for Asian countries, using frequencies ≥ 923 MHz
# countries: [bn, kh, hk, id, la, tw, th, vn]
# +++


# LoRa concentrator configuration.
[gateway.concentrator]

    # Multi spreading-factor channels (LoRa).
    multi_sf_channels=[
        923200000,
        923400000,
        923600000,
        923800000,
        924000000,
        924200000,
        924400000,
        924600000,
    ]

    # LoRa std channel (single spreading-factor).
    [gateway.concentrator.lora_std]
        frequency=924500000
        bandwidth=250000
        spreading_factor=7

    # FSK channel.
    [gateway.concentrator.fsk]
        frequency=924800000
        bandwidth=125000
        datarate=50000
