# +++
# name: United States 902-928 MHz, FSB 2 (used by TTN)
# description: TTN Community Network frequency plan for the United States and Canada, using sub-band 2
# countries: [bo, ca, co, cr, do, ec, gy, mx, pa, py, pe, pr, sr, us, uy, ve]
# +++


# LoRa concentrator configuration.
[gateway.concentrator]

    # Multi spreading-factor channels (LoRa).
    multi_sf_channels=[
        903900000,
        904100000,
        904300000,
        904500000,
        904700000,
        904900000,
        905100000,
        905300000,
    ]

    # LoRa std channel (single spreading-factor).
    [gateway.concentrator.lora_std]
        frequency=904600000
        bandwidth=500000
        spreading_factor=8
