# Metrics configuration.
#[metrics]

  # Metrics stored in Prometheus.
  #
  # These metrics expose information about the state of the ChirpStack Gateway Bridge
  # instance like number of messages processed, number of function calls, etc.
#  [metrics.prometheus]

    # Expose Prometheus metrics endpoint.
#    endpoint_enabled=false

    # The ip:port to bind the Prometheus metrics server to for serving the
    # metrics endpoint.
#    bind=""
