# This configuration file is intended for additional configuration
# that are not available in the standard setup.

# WARNING: do not repeat any section already defined in other files,
# otherwise the CSGB will not start

