#!/bin/sh
# Copyright (c) 2019-2020, Wifx Sàrl <info@wifx.net>
# All rights reserved.

alias printenv='$(which fw_printenv) -n'
alias setenv='$(which fw_setenv)'

fail() {
    echo -e "$1"
    # If sysfs not mounted, try to mount it
    mountpoint /sys > /dev/null 2>&1
    SYSFS_MOUNTED=$?
    if [ $SYSFS_MOUNTED -ne 0 ]; then
        mount -t sysfs sysfs /sys
        # Try again
        mountpoint /sys > /dev/null 2>&1
        SYSFS_MOUNTED=$?
    fi

    if [ $SYSFS_MOUNTED -eq 0 ] && [ -d /sys/class/leds/status ]; then
        # sysfs is mounted, try to signal failure using system status LED
        echo "timer" > /sys/class/leds/status/trigger
        echo "25" > /sys/class/leds/status/delay_on
        echo "2500" > /sys/class/leds/status/delay_off
    fi

    # Fallback to bash (useless without debug connector)
    /bin/bash
}

# Sources tools script
if [ ! -f /etc/os/.functions ]; then
    fail "OS tools script file not found\nPreinit work is impossible, abort"
fi
source /etc/os/.functions

# Global variables
BOOT_PART="0"
BOOT_PART_NAME="rootfsa"
UPGRADE_AVAILABLE="0"

preinit_dual_partition_read_info() {
    # Detect current running partition
    BOOT_PART=$(printenv mender_boot_part)
    if [ $? -ne 0 ]; then
        fail "Failed to read mender_boot_part from u-boot env"
    fi
    if [ $BOOT_PART -eq 1 ]; then
        BOOT_PART_NAME="rootfsb"
    fi

    # Detect if update is pending
    UPGRADE_AVAILABLE=$(printenv upgrade_available)
    if [ $? -ne 0 ]; then
        fail "Failed to read upgrade_available from u-boot env"
    fi
    if [ $UPGRADE_AVAILABLE -eq 1 ]; then
        echo "Upgrade is available"
    fi
}

preinit_initial_setup() {
     # Mount sysfs/procfs for machine detection and factory-reset
    mount -t sysfs sysfs /sys
    mount -t proc proc /proc

    # Create a read/write mount point of the rootfs
    mount -t tmpfs none /mnt
}

preinit_mount_data_volume() {
    # Create temporary work directory
    mkdir -p /mnt/ubidata

    # Mount ubidata volume
    echo "Mounting ubidata volume"
    mount -t ubifs ubi0:data /mnt/ubidata

    if [ $? -ne 0 ]; then
        echo "Error mounting data partition"
        return 1
    fi
    return 0
}

preinit_mount_overlay(){
    # Represent factory RO rootfs (ubi0:rootfsa or ubi0:rootfsb)
    mkdir /mnt/factory
    mount --bind / /mnt/factory

    # Represent final R/W rootfs (overlay:user)
    mkdir /mnt/rootfs

    # Create overlay directories
    mkdir -p /mnt/ubidata/overlay/user/{work,diff}
    mkdir -p /mnt/ubidata/overlay/config/{work,rootfsA,rootfsB}

    # Create overlay scaffold to be represented in final rootfs
    mkdir /mnt/scaffold
    # Consultative layers (overlayfs diff)
    mkdir -p /mnt/scaffold/var/lib/os/layers
    mkdir -p /mnt/scaffold/var/lib/os/layers/active/{factory,user,config}
    mkdir -p /mnt/scaffold/var/lib/os/layers/inactive/config

    # Create user overlay (main rootfs overlay)
    cd /mnt/ubidata/overlay/user
    mount -t overlay "overlay:user" -olowerdir=/mnt/scaffold:/mnt/factory,upperdir=diff,workdir=work /mnt/rootfs
    if [ $? -ne 0 ]; then
        echo "Error mounting user overlay"
        return 1
    fi

    # Create config overlay depending on main running partition
    cd /mnt/ubidata/overlay/config
    if [ $BOOT_PART -eq 0 ]; then
        mount -t overlay "overlay:config" -olowerdir=/mnt/factory/etc,upperdir=rootfsA,workdir=work /mnt/rootfs/etc
    else
        mount -t overlay "overlay:config" -olowerdir=/mnt/factory/etc,upperdir=rootfsB,workdir=work /mnt/rootfs/etc
    fi
    if [ $? -ne 0 ]; then
        echo "Error mounting config overlay"
        return 1
    fi

    # Going into final overlay rootfs
    cd /mnt/rootfs
    # Mount a new tmpfs to keep track of RO factory rootfs
    mount -t tmpfs none mnt
    mkdir -p mnt/factory

    # Execute the pivot root
    pivot_root . mnt/factory
    # Our "/" is now the overlay

    # Migrate system mounting points
    mount --move /mnt/factory/dev /dev
    mount --move /mnt/factory/proc /proc
    mount --move /mnt/factory/sys /sys

    # Migrate ubidata mounting point
    mkdir /mnt/ubidata
    mount --move /mnt/factory/mnt/ubidata /mnt/ubidata

    # Cleanup old rootfs
    umount /mnt/factory/mnt/factory
    umount /mnt/factory/mnt

    # Mount consultative layers
    mount --move -o ro /mnt/factory /var/lib/os/layers/active/factory
    mount --bind -o ro /mnt/ubidata/overlay/user/diff /var/lib/os/layers/active/user
    if [ $BOOT_PART -eq 0 ]; then
        # System A (partition 0) is currently running
        mount --bind -o ro /mnt/ubidata/overlay/config/rootfsA /var/lib/os/layers/active/config
        mount --bind -o ro /mnt/ubidata/overlay/config/rootfsB /var/lib/os/layers/inactive/config
    else
        # System B (partition 1) is currently running
        mount --bind -o ro /mnt/ubidata/overlay/config/rootfsA /var/lib/os/layers/inactive/config
        mount --bind -o ro /mnt/ubidata/overlay/config/rootfsB /var/lib/os/layers/active/config
    fi
}

preinit_manage_reset() {
    RESET_USER=0

    MACHINE_INFO=$(which machine-info)
    if [ $? -ne 0 ]; then
        echo "Can't find machine-info utils, abort"
        return 1
    fi

    # Detect boot_state from MCU
    BOOT_STATE=$(eval "$MACHINE_INFO read --noheader BOOT_STATE" 2> /dev/null)
    if [ $? -ne 0 ]; then
        echo "Error trying to read boot state:"
        echo $BOOT_STATE
        echo "abort"
        return 1
    fi

    if [ "$BOOT_STATE" == "factory" ]; then
        # we need a factory reset
        echo "Factory reset required, triggered by user"
        RESET_USER=1
    else
        FACTORY_RESET_PENDING=$(printenv factory_reset_pending)
        if [ "$FACTORY_RESET_PENDING" == "1" ]; then
            # Previous factory reset started but not completed
            echo "Factory reset required, previous did not complete"
        else
            # Test now first init flag presence
            os_first_init_has_started "/mnt/ubidata/overlay/user/diff/var/lib/os"
            if [ $? -eq 1 ]; then
                # Previous first init sequence has been done but not completed, need overlay cleaning
                echo "Factory reset required, triggered by first init unconsistent state"
            else
                echo "Factory reset not required, pass"
                return 0
            fi
        fi 
    fi

    # No need to revert the running partition since the factory reset
    # caused already a rollback state in u-boot. 
    # We are then already in previous working partition, we only need to remove
    # overlay content.

    # Launch the factory-reset script in overlay root
    echo "==== factory-reset ===="
    if [ $UPGRADE_AVAILABLE -eq 1 ]; then
        echo "Upgrade is pending while doing a factory reset, something which should not happen."
    fi
    # Keep track of the factory reset inside bootloader to ensure atomic operation
    echo "Beginning of procedure..."
    if [ "$FACTORY_RESET_PENDING" != "1" ]; then
        setenv factory_reset_pending 1
    fi
    echo "Removing existing overlay diff content"
    # Start cleaning system
    rm -rf /mnt/ubidata/overlay/user/diff/*
    rm -rf /mnt/ubidata/overlay/config/rootfsA/*
    rm -rf /mnt/ubidata/overlay/config/rootfsB/*
    echo "Disk synchronization"
    sync

    if [ $RESET_USER -eq 1 ]; then
        echo "Clearing factory reset state (mcu)"

        RET=$(eval "$MACHINE_INFO --reset" 2> /dev/null)
        if [ $? -ne 0 ]; then
            echo "Failed to clear factory reset state:"
            echo $RET
            echo "continue"
        fi
    fi

    echo "Factory reset completed"
    setenv factory_reset_pending
    echo "======== done ========="

    # No error
    return 0
}

echo "Switching to preinit script"

# Reading bootloader info like active root partition
preinit_dual_partition_read_info
echo "System running on ubi0:$BOOT_PART_NAME"

preinit_initial_setup
if [ $? -ne 0 ]; then
    fail "Fatal error during initial setup"
fi

# Mount the data volume
preinit_mount_data_volume
if [ $? -ne 0 ]; then
    fail "Fatal error during data volume mounting"
fi

# Detect machine and clear overlay diff if needed (factory reset)
# Also detect if first init process has been started and not cleanly
# completed
preinit_manage_reset
if [ $? -ne 0 ]; then
    fail "Fatal error during machine detection"
fi

# Mount the overlayfs
preinit_mount_overlay
if [ $? -ne 0 ]; then
    fail "Fatal error during overlay mount"
fi

if [ -e /etc/runlevels/default/firstboot ]; then
    # LED management (blinking if first init)
    os_mark_first_init_started
fi

# Cleanup system and ubidata mounting points
umount /proc
umount /sys
umount /mnt/ubidata
umount /mnt

# Start init process
exec chroot . sh -c "$(cat <<END
echo "Switching to init process"
exec /sbin/init
END
)" </dev/console >/dev/console 2>&1
