#!/bin/sh
# Copyright (c) 2019-2020, Wifx Sàrl <info@wifx.net>
# All rights reserved.

alias printenv='$(which fw_printenv) -n'
alias setenv='$(which fw_setenv)'

fail() {
    echo -e "$1"
    # If sysfs not mounted, try to mount it
    mountpoint /sys > /dev/null 2>&1
    SYSFS_MOUNTED=$?
    if [ $SYSFS_MOUNTED -ne 0 ]; then
        mount -t sysfs sysfs /sys
        # Try again
        mountpoint /sys > /dev/null 2>&1
        SYSFS_MOUNTED=$?
    fi

    if [ $SYSFS_MOUNTED -eq 0 ] && [ -d /sys/class/leds/status ]; then
        # sysfs is mounted, try to signal failure using system status LED
        echo "timer" > /sys/class/leds/status/trigger
        echo "25" > /sys/class/leds/status/delay_on
        echo "2500" > /sys/class/leds/status/delay_off
    fi

    # Fallback to bash (useless without debug connector)
    /bin/bash
}

# Sources tools script
if [ ! -f /etc/os/.functions ]; then
    fail "OS tools script file not found\nPreinit work is impossible, abort"
fi
source /etc/os/.functions

# Global variables
BOOT_PART="0"
BOOT_PART_NAME="rootfsA"
UPGRADE_AVAILABLE="0"

preinit_dual_partition_read_info() {
    # Detect current running partition
    BOOT_PART=$(printenv mender_boot_part)
    if [ $? -ne 0 ]; then
        fail "Failed to read mender_boot_part from u-boot env"
    fi
    if [ $BOOT_PART -eq 0 ]; then
        echo "Mounting overlay over ubi0_0 (rootfsA)"
    else
        echo "Mounting overlay over ubi0_1 (rootfsB)"
        BOOT_PART_NAME="rootfsB"
    fi

    # Detect if update is pending
    UPGRADE_AVAILABLE=$(printenv upgrade_available)
    if [ $? -ne 0 ]; then
        fail "Failed to read upgrade_available from u-boot env"
    fi
    if [ $UPGRADE_AVAILABLE -eq 1 ]; then
        echo "Upgrade is available"
    fi
}

preinit_mount_data_volume() {
    # Create temporary work directory
    mkdir -p /mnt/ubidata

    # Mount ubidata volume
    echo "Mounting ubidata volume"
    mount -t ubifs ubi0:data /mnt/ubidata

    if [ $? -ne 0 ]; then
        echo "Error mounting data partition"
        return 1
    fi
    return 0
}

preinit_mount_overlay(){
    # Create the required mount points for overlays
    mkdir -p /mnt/ubidata/overlay/user/{work,diff,merged}
    mkdir -p /mnt/ubidata/overlay/config/{work,rootfsA,rootfsB}

    # Create main user overlay which is mount on the top of current /
    # previously mounted on ubi0:rootfsa or ubi0:rootfsb by u-boot.
    cd /mnt/ubidata/overlay/user
    mount -t overlay "overlay:user" -olowerdir=/,upperdir=diff,workdir=work merged
    if [ $? -ne 0 ]; then
        echo "Error mounting overlay user"
        return 1
    fi

    # Create user config overlay depending on main running partition
    cd /mnt/ubidata/overlay/config
    if [ $BOOT_PART -eq 0 ]; then
        mount -t overlay "overlay:config" -olowerdir=/etc,upperdir=rootfsA,workdir=work /mnt/ubidata/overlay/user/merged/etc
    else
        mount -t overlay "overlay:config" -olowerdir=/etc,upperdir=rootfsB,workdir=work /mnt/ubidata/overlay/user/merged/etc
    fi
    if [ $? -ne 0 ]; then
        echo "Error mounting overlay config"
        return 1
    fi

    # Prepare for pivot_root
    cd /mnt/ubidata/overlay/user/merged

    # Create consultative layers mount points
    mkdir -p var/lib/os/layers/factory
    mkdir -p var/lib/os/layers/user
    mkdir -p var/lib/os/layers/config/{rootfsA,rootfsB}

    # Mount consultative layers
    mount --bind / var/lib/os/layers/factory
    mount --bind /mnt/ubidata/overlay/user/diff var/lib/os/layers/user
    mount --bind /mnt/ubidata/overlay/config/rootfsA var/lib/os/layers/config/rootfsA
    mount --bind /mnt/ubidata/overlay/config/rootfsB var/lib/os/layers/config/rootfsB

    mount --bind /dev dev

    # Keep track of current rootfs
    local OLD_ROOT=mnt/old
    mount -t tmpfs none mnt
    mkdir -p $OLD_ROOT

    # Execute the pivot
    pivot_root . $OLD_ROOT
    return 0
}

preinit_manage_reset() {
    RESET_USER=0

    MACHINE_INFO=$(which machine-info)
    if [ $? -ne 0 ]; then
        echo "Can't find machine-info utils, abort"
        return 1
    fi

    # Detect boot_state from MCU
    BOOT_STATE=$(eval "$MACHINE_INFO -n -f BOOT_STATE" 2> /dev/null)
    if [ $? -ne 0 ]; then
        echo "Error trying to read boot state:"
        echo $BOOT_STATE
        echo "abort"
        return 1
    fi

    if [ "$BOOT_STATE" == "factory" ]; then
        # we need a factory reset
        echo "Factory reset required, triggered by user"
        RESET_USER=1
    else
        FACTORY_RESET_PENDING=$(printenv factory_reset_pending)
        if [ "$FACTORY_RESET_PENDING" == "1" ]; then
            # Previous factory reset started but not completed
            echo "Factory reset required, previous did not complete"
        else
            # Test now first init flag presence
            os_first_init_has_started "/mnt/ubidata/overlay/user/diff/var/lib/os"
            if [ $? -eq 1 ]; then
                # Previous first init sequence has been done but not completed, need overlay cleaning
                echo "Factory reset required, triggered by first init unconsistent state"
            else
                echo "Factory reset not required, pass"
                return 0
            fi
        fi 
    fi

    # No need to revert the running partition since the factory reset
    # caused already a rollback state in u-boot. 
    # We are then already in previous working partition, we only need to remove
    # overlay content.

    # Launch the factory-reset script in overlay root
    echo "==== factory-reset ===="
    if [ $UPGRADE_AVAILABLE -eq 1 ]; then
        echo "Upgrade is pending while doing a factory reset, something which should not happen."
    fi
    # Keep track of the factory reset inside bootloader to ensure atomic operation
    echo "Beginning of procedure..."
    if [ "$FACTORY_RESET_PENDING" != "1" ]; then
        setenv factory_reset_pending 1
    fi
    echo "Removing existing overlay diff content"
    # Start cleaning system
    rm -rf /mnt/ubidata/overlay/user/diff/*
    rm -rf /mnt/ubidata/overlay/config/rootfsA/*
    rm -rf /mnt/ubidata/overlay/config/rootfsB/*
    echo "Disk synchronization"
    sync

    if [ $RESET_USER -eq 1 ]; then
        echo "Clearing factory reset state (mcu)"

        RET=$(eval "$MACHINE_INFO --reset" 2> /dev/null)
        if [ $? -ne 0 ]; then
            echo "Failed to clear factory reset state:"
            echo $RET
            echo "continue"
        fi
    fi

    echo "Factory reset completed"
    setenv factory_reset_pending
    echo "======== done ========="

    # No error
    return 0
}

echo "Switching to preinit script"

# Create a read/write mount point of the rootfs
mount -t tmpfs none /mnt
# Mount sysfs/procfs for machine detection and factory-reset
mount -t sysfs sysfs /sys
mount -t proc proc /proc

# Reading bootloader info like active root partition
preinit_dual_partition_read_info

# Mount the data volume
preinit_mount_data_volume
if [ $? -ne 0 ]; then
    fail "Fatal error during data volume mounting"
fi

# Detect machine and clear overlay diff if needed (factory reset)
# Also detect if first init process has been started and not cleanly
# completed
preinit_manage_reset
if [ $? -ne 0 ]; then
    fail "Fatal error during machine detection"
fi

# Clean useless mount points before the pivot
umount /sys /proc

# Mount the overlayfs
preinit_mount_overlay
if [ $? -ne 0 ]; then
    fail "Fatal error during overlay mount"
fi

if [ -e /etc/runlevels/default/firstboot ]; then
    # LED management (blinking if first init) needs the sysfs
    mount -t sysfs sysfs /sys
    os_mark_first_init_started
    umount /sys
fi

# Start init process (and unmount useless mount points)
exec chroot . sh -c "$(cat <<END
echo "Unmounting temporary directories"
umount /mnt/old/mnt/ubidata
umount /mnt/old/mnt
umount /mnt/old/dev
umount /mnt/old
umount /mnt
echo "Remounting overlay diff layers in read-only mode"
mount -o remount,ro,bind /var/lib/os/layers/user
mount -o remount,ro,bind /var/lib/os/layers/config/rootfsA
mount -o remount,ro,bind /var/lib/os/layers/config/rootfsB
echo "Switching to init process"
exec /sbin/init
END
)" <dev/console >dev/console 2>&1