# +++
# name: Europe 863-870 MHz (SF12 for RX2)
# description: Default frequency plan for Europe
# countries: [al, ad, ao, at, bh, be, ba, bw, bg, cg, hr, cy, cz, dk, ee, sz, fi, fr, gr, hu, is, ie, it, lv, ls, li, lt, lu, mg, mw, mt, mu, md, me, mz, na, nl, mk, ph, pl, pt, ro, ru, sa, rs, sc, sk, si, za, es, se, ch, tz, tr, ae, gb, va, zm, zw]
# +++


# LoRa concentrator configuration.
[gateway.concentrator]

    # Multi spreading-factor channels (LoRa).
    multi_sf_channels=[
        868100000,
        868300000,
        868500000,
        867100000,
        867300000,
        867500000,
        867700000,
        867900000,
    ]

    # LoRa std channel (single spreading-factor).
    [gateway.concentrator.lora_std]
        frequency=868300000
        bandwidth=250000
        spreading_factor=7

    # FSK channel.
    [gateway.concentrator.fsk]
        frequency=868800000
        bandwidth=125000
        datarate=50000
