description: ChirpStack MQTT Forwarder with concentratord
autostart: true
log: true
jobs:
    concentratord:
        description: The daemon receiving data from the LoRa concentrator (SX13XX) and forwarding to the Gateway Bridge
        enabled: true
        boot-order: 0
        process:
            run-mode: exec
            program-path: /opt/chirpstack-concentratord/chirpstack-concentratord
            program-arguments: >-
              -c /etc/opt/chirpstack-concentratord/00-concentratord.toml
              -c /etc/opt/chirpstack-concentratord/10-gateway.toml
              -c /etc/opt/chirpstack-concentratord/11-location.toml
              -c /etc/opt/chirpstack-concentratord/channels/channels.toml
            delays:
                start: 3000
                term: 1000
                restart: 5000
    gateway-mesh:
        description: Gateway Mesh is in between the concentrator daemon and the MQTT Forwarder, handling mesh network if configured
        enabled: false
        boot-order: 1
        process:
            run-mode: exec
            program-path: /opt/chirpstack-gateway-mesh/chirpstack-gateway-mesh
            program-arguments: >-
              -c /etc/opt/chirpstack-gateway-mesh/10-logging.toml
              -c /etc/opt/chirpstack-gateway-mesh/20-mesh.toml
              -c /etc/opt/chirpstack-gateway-mesh/21-mesh-proxy-api.toml
              -c /etc/opt/chirpstack-gateway-mesh/30-backend.toml
              -c /etc/opt/chirpstack-gateway-mesh/40-events.toml
              -c /etc/opt/chirpstack-gateway-mesh/50-commands.toml
              -c /etc/opt/chirpstack-gateway-mesh/mappings.toml
            delays:
                start: 1000
                term: 1000
                restart: 5000
    mqtt-forwarder:
        description: MQTT Forwarder receiveing the concentrator daemon packets and sending them to the ChirpStack Network Server
        enabled: true
        boot-order: 2
        process:
            run-mode: exec
            program-path: /opt/chirpstack-mqtt-forwarder/chirpstack-mqtt-forwarder
            program-arguments: >-
              -c /etc/opt/chirpstack-mqtt-forwarder/10-logging.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/20-mqtt.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/30-backend.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/31-filters.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/40-metadata.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/50-commands.toml
              -c /etc/opt/chirpstack-mqtt-forwarder/60-callbacks.toml
            delays:
                start: 1000
                term: 1000
                restart: 5000
