# Gateway metadata configuration.
[metadata]

  # Static key / value metadata.
  [metadata.static]
      
    # Example:
    # maintainer="john.doe@acme.com"


  # Commands returning metadata.
  [metadata.commands]

    # Examples:
    # uptime=["/usr/bin/uptime", "-p"]

    # antenna_gain=["/usr/bin/manager", "-o=standard lora hardware antenna"]
