# Servers to forward the data to using UDP.
# This section can be repeated.
[[udp_bridge.servers]]
  # Server (hostname:port).
  server="eu1.cloud.thethings.network:1700"

  # Keepalive interval (seconds).
  #
  # In this interval, the ChirpStack UDP Bridge will send keepalive
  # frames to the server, which must be answered by an acknowledgement.
  keepalive_interval_secs=10

  # Max. allowed keepalive failures.
  #
  # After the max. number has been reached, the ChirpStack UDP Bridge will
  # 're-connect' to the server, meaning it will also re-resolve the DNS in case
  # the server address is a hostname.
  keepalive_max_failures=12
